server:
  port: 8083
spring:
  application:
    name: auction-service
  datasource:
    url: jdbc:postgresql://localhost:5435/auction
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

relicarium:
  security:
    jwt:
      secret: relicarium-dev-jwt-secret-min-32-characters-long
      issuer: relicarium
      access-token-ttl: PT8H