server:
  port: 8081

spring:
  application:
    name: pledge-service

  datasource:
    url: jdbc:postgresql://localhost:5433/pledge
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
relicarium:
  ledger:
    base-url: http://localhost:8082
  auction:
    base-url: http://localhost:8083